name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Asegúrate de estar usando la rama principal correcta

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Set up Git configuration
        run: |
          git config --global user.name "mandycs"
          git config --global user.email "mandycortessimon@gmail.com"

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/mandycs/noscasamosel13deseptiembre.git
          npm run deploy
